[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[theme]
primaryColor = "#f47322"
backgroundColor = "#fbfaf7"
secondaryBackgroundColor = "#ffffff"
textColor = "#111111"
font = "sans serif"
